import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";

const login = await readFile("app/(auth)/login.tsx", "utf8");
const register = await readFile("app/(auth)/register.tsx", "utf8");
const webApp = await readFile("src/web/App.tsx", "utf8");
const webStyles = await readFile("src/web/styles.css", "utf8");
const authApi = await readFile("src/features/auth/auth.api.ts", "utf8");
const endpoints = await readFile("src/services/api/endpoints.ts", "utf8");

assert.match(register, /initialMode="register"/, "register route should start in register mode");
assert.match(login, /reservedNameField/, "auth form should reserve name field space to avoid layout jumps");
assert.match(login, /authCardHeight/, "auth card should use a shared fixed height token");
assert.match(login, /height:\s*authCardHeight/, "auth card height should not change between login and register");
assert.match(login, /reservedNameField:\s*{[\s\S]*height:/, "reserved register field should use fixed height, not minHeight");
assert.doesNotMatch(login, /google@barlog\.local/, "Google login must not use simulated local credentials");
assert.match(login, /openAuthSessionAsync/, "Google login should launch an OAuth auth session");
assert.match(login, /googleAuthPanel/, "Google OAuth should show an in-card status panel");
assert.match(login, /googleAuthStatus/, "Google OAuth should expose visible status text");
assert.match(webApp, /auth-register-field/, "web auth should always reserve register field space");
assert.match(webApp, /Enter with Google/, "web auth should show an Enter with Google button");
assert.match(webApp, /startGoogleAuth/, "web auth should start Google OAuth through the auth API");
assert.match(webStyles, /\.auth-screen[\s\S]*grid-template-rows:/, "web auth screen should pin the brand and card rows");
assert.match(webStyles, /\.brand-block[\s\S]*height:/, "web auth brand block should have fixed height");
assert.match(webStyles, /\.auth-card[\s\S]*height:/, "web auth card should have fixed height");
assert.match(webStyles, /\.auth-register-field\s*{[\s\S]*height:\s*0/, "web login mode should collapse the register field so lower inputs move up");
assert.match(webStyles, /\.auth-register-field\.is-visible\s*{[\s\S]*height:\s*66px/, "web register mode should expand the register field inside the fixed card");
assert.match(webStyles, /\.auth-message-slot[\s\S]*height:/, "web auth message row should reserve fixed space");
assert.doesNotMatch(webStyles, /\.google-login-button\s*{[\s\S]*background:\s*#f7efe7/, "web Google button should not use a bright light background");
assert.match(webStyles, /\.google-login-button\s*{[\s\S]*background:\s*#21100e/, "web Google button should use the darker neutral button palette");
assert.match(webApp, /<span><b>{index \+ 1}<\/b><\/span>/, "map pin number should have its own element so it can rotate independently");
assert.match(webStyles, /\.map-pin b\s*{[\s\S]*transform:\s*rotate\(45deg\)/, "map pin number should rotate clockwise 45deg");
assert.match(webStyles, /\.map-pin b\s*{[^}]*color:\s*#fff;/, "map pin number should use white");
assert.match(webApp, /Wine,/, "Diary total logs stat should use Wine icon");
assert.match(webApp, /MapPin,/, "Diary explored stat should use MapPin icon");
assert.match(webApp, /stat-card \$\{active \? "active" : ""\}/, "Diary stat cards should expose active state");
assert.match(webApp, /unit="LOGS"/, "Total logs stat should show LOGS unit");
assert.match(webApp, /unit="BARS"/, "Explored stat should show BARS unit");
assert.match(webApp, /unit="PTS"/, "Avg rating stat should show PTS unit");
assert.match(webApp, /statusLabel="RATING"/, "Avg rating stat should show RATING inactive label");
assert.match(webStyles, /\.stat-card\s*{[\s\S]*cursor:\s*pointer/, "Diary stat cards should be clickable buttons");
assert.match(webStyles, /\.stat-card\s*{[^}]*background:\s*rgba\(18,\s*9,\s*8,\s*0\.42\)/, "Inactive Diary stat cards should be closer to the page background");
assert.match(webStyles, /\.stat-card\s*{[^}]*box-shadow:\s*none/, "Inactive Diary stat cards should not look heavier than the background");
assert.match(webStyles, /\.stat-card\.active\s*{[\s\S]*scale:\s*1\.03/, "Diary stat card active state should scale up");
assert.match(webStyles, /\.stat-icon\s*{/, "Diary stat cards should style icon shells");
assert.match(webStyles, /\.stat-pulse\s*{[\s\S]*animation:\s*stat-pulse/, "Active Diary stat cards should show a pulsing dot");
assert.match(webStyles, /\.calendar-card\s*{[\s\S]*background:\s*rgba\(18,\s*9,\s*8,\s*0\.42\)/, "Diary calendar card should use the transparent background treatment");
assert.match(webStyles, /\.calendar-card\s*{[\s\S]*border:\s*0/, "Diary calendar card border should be removed");
assert.match(webStyles, /\.calendar-card\s*{[\s\S]*box-shadow:\s*none/, "Diary calendar card should not use the shared card shadow");
assert.match(webStyles, /\.rope-scroll\s*{[\s\S]*background:\s*rgba\(9,\s*3,\s*2,\s*0\.36\)/, "Diary calendar scroll area should also be transparent");
assert.match(webStyles, /\.rope-scroll\s*{[\s\S]*border:\s*0/, "Diary calendar scroll border should be removed");
assert.match(authApi, /startGoogleAuth/, "auth API should expose Google OAuth start");
assert.match(endpoints, /googleStart/, "endpoints should include the Google OAuth start path");

console.log("auth UI checks passed");
